### ISSUE TITLE
Getting TypeError: drop() takes from 1 to 2 positional arguments but 3 were given while running exploration.py

### ISSUE THREAD

**Issue by tanjimanasreen** [etsoukanara/GraphTempo#1]
Hi, 

I am trying to run the exploration.py according to the instructions given in your Readme, but I am getting this TypeError for drop(). 

<img width="946" alt="Screenshot 2023-11-20 at 11 17 17 PM" src="https://github.com/etsoukanara/graphtempo/assets/29819845/f6736a2f-5ab2-4853-a0f0-d6f77e3dfb60">

I am working with the below versions:
`Python 3.9.6, numpy==1.26.0, ray==2.7.1, pandas==2.1.3, modin==0.24.1`

Thank you.

**Comment by etsoukanara** [comment]
@tanjimanasreen hello and thank you for your interest in our work!
It seems to be a matter of the python version your are using. GraphTempo uses python 3.7.9.
So, you have to either downgrade to 3.7.9, or simply replace .drop('count', 1) with .drop('count', axis=1) in the code.
Please let me know if the issue is resolved.

**Comment by tanjimanasreen** [comment]
Hi, yes, the problem was solved after updating the drop(). Thank you very much!
